[rhel_servers]
# server-1 ansible_host=10.0.1.10
# server-2 ansible_host=10.0.1.11
# server-3 ansible_host=10.0.1.12

[rhel_servers:vars]
ansible_user=rancher
ansible_become=true
ansible_become_method=sudo
