[rke2_servers]
rke2-server-1 ansible_host=10.0.1.10
rke2-server-2 ansible_host=10.0.1.11
rke2-server-3 ansible_host=10.0.1.12

[rke2_agents]
rke2-agent-1 ansible_host=10.0.1.20
rke2-agent-2 ansible_host=10.0.1.21
rke2-agent-3 ansible_host=10.0.1.22

[rke2_cluster:children]
rke2_servers
rke2_agents

[rke2_cluster:vars]
ansible_user=rancher
ansible_become=true
ansible_become_method=sudo
rke2_service_server=rke2-server
rke2_service_agent=rke2-agent
kubeconfig_path=/etc/rancher/rke2/rke2.yaml
kubectl_bin=/var/lib/rancher/rke2/bin/kubectl
